lib/ashtray_web/router.ex
defmodule AshtrayWeb.Router do
  use AshtrayWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug AshtrayWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AshtrayWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  scope "/auth", AshtrayWeb do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :new
    delete "/", AuthController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", AshtrayWeb do
  #   pipe_through :api
  # end
end

lib/ashtray/accounts/accounts.ex
defmodule Ashtray.Accounts do
  import Ecto.Query, warn: false
  alias Ashtray.Repo

  alias Ashtray.Accounts.User

  def get_user(id), do: Repo.get(User, id)

  def get_user_by(attrs), do: Repo.get_by(User, attrs)

  def register_user(attrs \\ %{}) do
    %User{}
    |> User.changeset(attrs)
    |> Repo.insert()
  end
end

lib/ashtray/accounts/user.ex
defmodule Ashtray.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset


  schema "users" do
    field :avatar, :string
    field :email, :string
    field :name, :string
    field :handle, :string

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:name, :email, :avatar, :handle])
    |> validate_required([:name, :email, :avatar, :handle])
  end
end

lib/ashtray/application.ex
defmodule Ashtray.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      Ashtray.Repo,
      # Start the endpoint when the application starts
      AshtrayWeb.Endpoint
      # Starts a worker by calling: Ashtray.Worker.start_link(arg)
      # {Ashtray.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Ashtray.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    AshtrayWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/ashtray/repo.ex
defmodule Ashtray.Repo do
  use Ecto.Repo,
    otp_app: :ashtray,
    adapter: Ecto.Adapters.Postgres
end

lib/ashtray_web/controllers/auth_controller.ex
defmodule AshtrayWeb.AuthController do
  use AshtrayWeb, :controller
  plug Ueberauth

  alias AshtrayWeb.Auth

  def new(%{assigns: %{ueberauth_auth: auth}} = conn, _params) do
    conn
    |> Auth.login_or_register(auth.info)
    |> redirect(to: Routes.page_path(conn, :index))
  end

  def delete(conn, _params) do
    conn
    |> Auth.logout()
    |> redirect(to: Routes.page_path(conn, :index))
  end
end

lib/ashtray_web/controllers/page_controller.ex
defmodule AshtrayWeb.PageController do
  use AshtrayWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/ashtray_web/views/error_view.ex
defmodule AshtrayWeb.ErrorView do
  use AshtrayWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/ashtray_web/views/layout_view.ex
defmodule AshtrayWeb.LayoutView do
  use AshtrayWeb, :view
end

lib/ashtray_web/views/page_view.ex
defmodule AshtrayWeb.PageView do
  use AshtrayWeb, :view
end

lib/ashtray_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Ashtray</title>
  <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
</head>

<body>
  <div id="app">
    <div class="grid-hero">
      <div class="container grid-xl">
        <header class="navbar py-2 px-2">
          <section class="navbar-section">
            <a href="/" class="navbar-brand d-flex">
              <img src="/images/logo.svg" width="48" alt="Ashtray">
              <div class="pt-2 ml-2 h4 text-normal text-dark"> Ashtray </div>
            </a>
          </section>
          <section class="navbar-section">
            <%= if @current_user  do %>
            <%= link "Log Out", to: Routes.auth_path(@conn, :delete), method: :delete, class: "btn btn-sm btn-link text-error text-uppercase mr-2" %>
              <figure class="avatar ml-2">
                <img src="<%= @current_user.avatar %>" alt="" />
              </figure>
            <a href="https://github.com/<%= @current_user.handle %>" target="_blank">
              <span class="ml-2">
                <%= @current_user.handle %>
              </span>
            </a>
            <% else %>
            <%= @current_user.handle %>
            <%= link "GitHub Login", to: Routes.auth_path(@conn, :request, "github"), class: "btn btn-primary text-uppercase" %>
            <% end %>
          </section>
        </header>
      </div>
    </div>
    <main>
      <div class="container grid-xl">
        <div class="columns">
          <div class="column col-6 col-mx-auto">
            <%= if error = get_flash(@conn, :error)  do %>
            <div class="toast toast-error">
              <%= error %>
            </div>
            <% end %>
            <%= if info = get_flash(@conn, :info)  do %>
            <div class="toast toast-success">
              <%= info %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="mt-2">
          <%= render @view_module, @view_template, assigns %>
        </div>
      </div>
    </main>
  </div>
  <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>
    ">
  </script>
</body>

</html>

lib/ashtray_web/templates/page/index.html.eex
<h6>Hello, Ashtray!</h6>